// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpAgent.Infrastructure.Persistence;

#nullable disable

namespace SharpAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SharpAgentDbContext))]
    [Migration("20260824033206_Phase2WorkspaceSafety")]
    partial class Phase2WorkspaceSafety
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SharpAgent.Domain.Approvals.ApprovalRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedPathsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedAtUtc")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("RunId", "Status");

                    b.HasIndex("SessionId", "Status");

                    b.ToTable("ApprovalRequests", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Auditing.AuditEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Changes.ChangeSet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("ChangeSets", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Changes.FileChange", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterContentText")
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffText")
                        .HasMaxLength(32000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBinary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangeSetId");

                    b.ToTable("FileChanges", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Policies.PolicyProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ApprovalExpiryMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxEstimatedCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRunDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxToolCalls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PolicyProfiles", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Profiles.ModelProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigReference")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndpointKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("ModelProfiles", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Sessions.AgentRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelRequestedAtUtc")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextSummary")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedAtUtc")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionEnvironmentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalSummary")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeSourceRunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Planning', 'Executing', 'AwaitingApproval', 'Reviewing')");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("AgentRuns", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Sessions.RunLease", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AcquiredAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedAtUtc")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"ReleasedAtUtc\" IS NULL");

                    b.ToTable("RunLeases", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Sessions.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveRunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivedAtUtc")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastEventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastInstruction")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Todos.TodoItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("TodoItems", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Tools.ToolExecution", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedAtUtc")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputPreview")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OutputTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolicyOutcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RedactionApplied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("ToolExecutions", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Usage.UsageRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextCompactions")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolCalls")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("SessionId");

                    b.ToTable("UsageRecords", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedPathsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalRootPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultModelProfileId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("SharpAgent.Domain.Changes.FileChange", b =>
                {
                    b.HasOne("SharpAgent.Domain.Changes.ChangeSet", null)
                        .WithMany("Files")
                        .HasForeignKey("ChangeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpAgent.Domain.Sessions.AgentRun", b =>
                {
                    b.HasOne("SharpAgent.Domain.Sessions.Session", null)
                        .WithMany("Runs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpAgent.Domain.Changes.ChangeSet", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("SharpAgent.Domain.Sessions.Session", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}

